linters:
  EmptyLineBetweenBlocks:
    enabled: false
  Indentation:
    width: 2
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    max_depth: 5

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern
  StringQuotes:
    enabled: false
    style: single_quotes # or double_quotes
