linters:
  BorderZero:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  Indentation:
    width: 2
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false
    max_depth: 6

  CapitalizationInSelector:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern
  StringQuotes:
    enabled: false
    style: single_quotes # or double_quotes
